# Generated by Django 4.2 on 2023-04-22 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('name', models.CharField(default='', max_length=32)),
                ('number', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('registration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Voter',
                'db_table': 'Voter',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.IntegerField(default=0)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='api_rest.candidate')),
            ],
        ),
    ]
